name: Build and Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12, 14, 16, 18]
        keycloak:
          - "5.0.0"
          - "6.0.1"
          - "7.0.1"
          - "8.0.2"
          - "9.0.3"
          - "10.0.2"
          - "11.0.3"
          - "12.0.4"
          - "13.0.1"
          - "14.0.0"
          - "15.1.1"
          - "16.1.1"
          - "17.0.1"

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true
      - name: Test
        run: |
          cd testing
          docker-compose up -d
          cd ..
          npm test
        env:
          KEYCLOAK_VERSION: ${{ matrix.keycloak }}
          CI: true
